### ISSUE TITLE
Fix IR dump to be machine-independent (in seedimg.cpp)

### ISSUE THREAD

**Issue by telugu-boy** [telugu-boy/seedimg#3]
eg. use htonl, etc to convert numbers to endian independant representation in files, same with pixel data

**Comment by tripulse** [comment]
I'd have a objection against this. The [**Suckless Farbfeld**][0] format is very similar to the **IR dump** format. But then again, pixel format used in Farbfeld doesn't match the IR.

[0]: https://suckless.org/

**Comment by tripulse** [comment]
We could use this following specification for the IR format.
|      Field      |    Size (bytes)   |            Description            |
|-----------------|------------|-----------------------------------|
|      Width      |     4      |  Positive horizontal axis bound   |
|      Height     |     4      |  Positive vertical   axis bound   |
|      Data      | *Width* × *Height* × 4 |   1D contagious pixel data with 8-bit precision in RGBA order     |

Note that, all multibyte integrals fields are to be coded with big-endian order.

**Comment by telugu-boy** [comment]
Okay, most code can be copy pasted from farbfeld module. Make a PR.
