### ISSUE TITLE
CCONV: Implement YCbCr <-> RGB with a lookup table instead of multiplication.

### ISSUE THREAD

**Issue by telugu-boy** [telugu-boy/seedimg#39]

**Comment by tripulse** [comment]
Then we've to make a 16MiB lookup table for *YCbCr -> RGB* and back.

**Comment by telugu-boy** [comment]
No

**Comment by telugu-boy** [comment]
Y R
Y G
Y B

Cr R
Cr G
Cr B

Cb R
Cb G
Cb B

So total 9 LUTs, sizeof(int) * 9 * 255

**Comment by telugu-boy** [comment]
About 10kb in the binary

**Comment by telugu-boy** [comment]
And there'd be one back as well. So in total 20kb

**Comment by tripulse** [comment]
Hm, ok, that's good.

**Comment by telugu-boy** [comment]
ycbcr to rgb has been implemented. Next is rgb to ycbcr, and resource headers will follow the naming convention `from_(input colourspace)_lut.rh`.

**Comment by telugu-boy** [comment]
Done.
