### ISSUE TITLE
Multithread blurring

### ISSUE THREAD

**Issue by telugu-boy** [telugu-boy/seedimg#4]
Would be as simple as to  put the method and res_img as parameter into another method and call the function in seedimg::img to split into portions and process from there. But, blurring is fast enough so this can be addressed later.

**Comment by tripulse** [comment]
If it's a convolution, it must have other pixels to overlap forwhich slicing all up makes it difficult and will yield invalid results.

**Comment by telugu-boy** [comment]
This box blur implementation is linear so we can slice it up one for horizontal and vertical.

**Comment by tripulse** [comment]
Hm, ok then.

**Comment by telugu-boy** [comment]
Done.
